# In TypeScript actions, `dist/` is a special directory. When you reference
# an action with the `uses:` property, `dist/index.js` is the code that will be
# run. For this project, the `dist/index.js` file is transpiled from other
# source files. This workflow ensures the `dist/` directory contains the
# expected transpiled code.
#
# If this workflow is run from a feature branch, it will act as an additional CI
# check and fail if the checked-in `dist/` directory does not match what is
# expected from the build. If the workflow is run from a branch created by
# Dependabot, it will automatically rebuild and push the updated `dist/`
# directory.
name: Check Transpiled JavaScript

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - tsconfig.json
  pull_request:
    paths:
      - '**.ts'
      - tsconfig.json
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check-dist:
    name: Check dist/
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Build dist/ Directory
        id: build
        run: npm run bundle

      # This will fail the workflow if the PR wasn't created by Dependabot.
      - name: Compare Directories
        id: diff
        continue-on-error:
          ${{ startsWith(github.head_ref, 'dependabot/') &&
          github.event.pull_request.user.login == 'dependabot[bot]' }}
        run: |
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --ignore-space-at-eol --text dist/
            exit 1
          fi

      # If `dist/` was different than expected, and this was not a Dependabot
      # PR, upload the expected version as a workflow artifact.
      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
        name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

      # If `dist/` was different than expected, and this was a Dependabot PR,
      # push the update to the Dependabot branch.
      - if: ${{ success() && steps.diff.outcome == 'failure' }}
        name: Update Dependabot PR
        id: update
        run: |
          git add dist/
          git commit -m '[dependabot skip] Rebuild action'
          git push
